pull_request_rules:
  - name: Automatic merge dependabot
    conditions:
      - author=dependabot[bot]
      - status-success=buildkite/osso
    actions:
      merge:
        method: merge
        strict: true